<a href="https://colab.research.google.com/github/fernandouribeu/analisis_datos/blob/main/lab01_ad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

En la seccion anterior se importo pandas y numpy

In [7]:
df = pd.read_csv("clientes_retail.csv")

Se importo el csv como data frame

In [9]:
df.head()

,customer_id,age,gender,education,marital_status,income_clp,region,registration_date,total_purchases,total_spent_clp,online_purchases,store_purchases,complaints,satisfaction_score,last_purchase_days
0,C00001,47,Femenino,Media,Soltero,781889.0,Biobío,2024-02-05,12,537694,7,5,0,4.0,206
1,C00002,40,Femenino,Media,Soltero,1242577.0,Araucanía,2020-02-11,9,862822,6,11,0,4.0,242
2,C00003,49,Masculino,Media,Soltero,1347579.0,Araucanía,2020-10-12,20,1195473,5,4,1,4.0,306
3,C00004,60,Masculino,Técnica,Casado,686279.0,Biobío,2023-10-13,15,1571007,4,8,0,3.0,184
4,C00005,39,Femenino,Universitaria,Casado,1394730.0,Biobío,2018-01-29,14,410407,7,6,0,3.0,128

In [12]:
df.shape

(1020, 15)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         1020 non-null   object
 1   age                 1020 non-null   int64
 2   gender              1020 non-null   object
 3   education           969 non-null    object
 4   marital_status      1020 non-null   object
 5   income_clp          916 non-null    float64
 6   region              1020 non-null   object
 7   registration_date   1020 non-null   object
 8   total_purchases     1020 non-null   int64
 9   total_spent_clp     1020 non-null   int64
 10  online_purchases    1020 non-null   int64
 11  store_purchases     1020 non-null   int64
 12  complaints          1020 non-null   int64
 13  satisfaction_score  990 non-null    float64
 14  last_purchase_days  1020 non-null   int64
dtypes: float64(2), int64(7), object(6)
memory usage: 119.7+ KB

In [13]:
df.describe()

,age,income_clp,total_purchases,total_spent_clp,online_purchases,store_purchases,complaints,satisfaction_score,last_purchase_days
count,1020.000000,9.160000e+02,1020.000000,1.020000e+03,1020.000000,1020.000000,1020.000000,990.000000,1020.000000
mean,42.037255,1.344718e+06,15.137255,1.065511e+06,7.025490,8.058824,1.103922,3.665657,185.896078
std,12.772355,1.009656e+06,3.782713,2.264178e+06,2.691414,2.815991,1.852507,1.081292,102.958374
min,5.000000,-5.000000e+05,3.000000,-3.000000e+04,0.000000,1.000000,-1.000000,0.000000,2.000000
25%,34.000000,8.591062e+05,12.000000,5.354258e+05,5.000000,6.000000,0.000000,3.000000,100.000000
50%,42.000000,1.200099e+06,15.000000,8.158990e+05,7.000000,8.000000,1.000000,4.000000,194.000000
75%,49.000000,1.618652e+06,18.000000,1.223987e+06,9.000000,10.000000,2.000000,4.000000,274.000000
max,150.000000,2.500000e+07,27.000000,5.000000e+07,18.000000,19.000000,50.000000,10.000000,364.000000

In [14]:
df.isnull().sum()

customer_id             0
age                     0
gender                  0
education              51
marital_status          0
income_clp            104
region                  0
registration_date       0
total_purchases         0
total_spent_clp         0
online_purchases        0
store_purchases         0
complaints              0
satisfaction_score     30
last_purchase_days      0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(20)