<a href="https://colab.research.google.com/github/fernandouribeu/analisis_datos/blob/main/Laboratorio_1_Notebook_Template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratorio Práctico 1 · Calidad y exploración de datos

**Curso:** Análisis de Datos  
**Programa:** Magíster en Data Science  
**Universidad del Desarrollo**

**Nombre estudiante:** Fernando Uribe
**Fecha:** 08/08/2026

---

## Contexto del problema

Describa brevemente el contexto empresarial del dataset analizado y el objetivo del laboratorio.

Preguntas orientadoras:

- ¿Qué representa este conjunto de datos?
- ¿Qué problema de análisis se busca abordar?
- ¿Por qué es importante evaluar la calidad de los datos antes de continuar?

## 1. Importación de librerías

Importe las librerías necesarias para realizar el análisis.

Se recomienda utilizar:

- pandas
- numpy
- matplotlib
- seaborn

In [6]:
# Importación de librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

#Se importaron las librerias pandas, numpy, matplotlib y seaborn

## 2. Carga del dataset

Cargue el archivo `clientes_retail.csv` y muestre las primeras observaciones.

Incluya una breve descripción del proceso de carga.

In [2]:
#Carga de la carpeta a drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
# Carga del dataset
df = pd.read_csv("/content/drive/MyDrive/Analisis de Datos/clientes_retail.csv")

## 3. Exploración inicial

Analice las características generales del dataset:

- cantidad de registros;
- cantidad de variables;
- nombres de columnas;
- primeros registros.

In [14]:
# Exploración inicial

#cantidad de registros;
#cantidad de variables;
df.shape

(1020, 15)

In [15]:
#nombres de columnas;
df.columns.tolist()

['customer_id',
 'age',
 'gender',
 'education',
 'marital_status',
 'income_clp',
 'region',
 'registration_date',
 'total_purchases',
 'total_spent_clp',
 'online_purchases',
 'store_purchases',
 'complaints',
 'satisfaction_score',
 'last_purchase_days']

In [19]:
#primeros registros.
df.head()

,customer_id,age,gender,education,marital_status,income_clp,region,registration_date,total_purchases,total_spent_clp,online_purchases,store_purchases,complaints,satisfaction_score,last_purchase_days
0,C00001,47,Femenino,Media,Soltero,781889.0,Biobío,2024-02-05,12,537694,7,5,0,4.0,206
1,C00002,40,Femenino,Media,Soltero,1242577.0,Araucanía,2020-02-11,9,862822,6,11,0,4.0,242
2,C00003,49,Masculino,Media,Soltero,1347579.0,Araucanía,2020-10-12,20,1195473,5,4,1,4.0,306
3,C00004,60,Masculino,Técnica,Casado,686279.0,Biobío,2023-10-13,15,1571007,4,8,0,3.0,184
4,C00005,39,Femenino,Universitaria,Casado,1394730.0,Biobío,2018-01-29,14,410407,7,6,0,3.0,128

## 4. Análisis de estructura

Evalúe:

- tipos de datos;
- variables numéricas;
- variables categóricas;
- posibles problemas de formato.

Explique los principales hallazgos.

In [18]:
# Estructura del dataset
df.info()
#tipos de datos;

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         1020 non-null   object
 1   age                 1020 non-null   int64
 2   gender              1020 non-null   object
 3   education           969 non-null    object
 4   marital_status      1020 non-null   object
 5   income_clp          916 non-null    float64
 6   region              1020 non-null   object
 7   registration_date   1020 non-null   object
 8   total_purchases     1020 non-null   int64
 9   total_spent_clp     1020 non-null   int64
 10  online_purchases    1020 non-null   int64
 11  store_purchases     1020 non-null   int64
 12  complaints          1020 non-null   int64
 13  satisfaction_score  990 non-null    float64
 14  last_purchase_days  1020 non-null   int64
dtypes: float64(2), int64(7), object(6)
memory usage: 119.7+ KB

In [21]:
#variables numéricas;
df.describe()

,age,income_clp,total_purchases,total_spent_clp,online_purchases,store_purchases,complaints,satisfaction_score,last_purchase_days
count,1020.000000,9.160000e+02,1020.000000,1.020000e+03,1020.000000,1020.000000,1020.000000,990.000000,1020.000000
mean,42.037255,1.344718e+06,15.137255,1.065511e+06,7.025490,8.058824,1.103922,3.665657,185.896078
std,12.772355,1.009656e+06,3.782713,2.264178e+06,2.691414,2.815991,1.852507,1.081292,102.958374
min,5.000000,-5.000000e+05,3.000000,-3.000000e+04,0.000000,1.000000,-1.000000,0.000000,2.000000
25%,34.000000,8.591062e+05,12.000000,5.354258e+05,5.000000,6.000000,0.000000,3.000000,100.000000
50%,42.000000,1.200099e+06,15.000000,8.158990e+05,7.000000,8.000000,1.000000,4.000000,194.000000
75%,49.000000,1.618652e+06,18.000000,1.223987e+06,9.000000,10.000000,2.000000,4.000000,274.000000
max,150.000000,2.500000e+07,27.000000,5.000000e+07,18.000000,19.000000,50.000000,10.000000,364.000000

In [29]:
#variables categóricas;
df.describe(include=['object'])

,customer_id,gender,education,marital_status,region,registration_date
count,1020,1020,969,1020,1020,1020
unique,1000,7,4,4,7,857
top,C00974,Femenino,Técnica,Viudo,Metropolitana,05-11-2022
freq,2,495,346,282,257,5

Posibles errores de formato:

*   El campo de income_clp permite decimales pero el peso como divisa no es fraccionable.
*   El campo de income_clp,total_spent_clp y complains permiten valores negativos

## 5. Evaluación de calidad de datos

Realice un diagnóstico considerando:

- valores faltantes;
- registros duplicados;
- inconsistencias categóricas;
- valores extremos;
- problemas de tipos de datos.

Incluya evidencia y explique el posible impacto de cada problema.

In [30]:
# Calidad de datos

#valores faltantes;
df.isnull().sum()

customer_id             0
age                     0
gender                  0
education              51
marital_status          0
income_clp            104
region                  0
registration_date       0
total_purchases         0
total_spent_clp         0
online_purchases        0
store_purchases         0
complaints              0
satisfaction_score     30
last_purchase_days      0
dtype: int64

In [31]:
#registros duplicados;
df.duplicated().sum()

np.int64(20)

In [34]:
df[df.duplicated(keep=False)]

,customer_id,age,gender,education,marital_status,income_clp,region,registration_date,total_purchases,total_spent_clp,online_purchases,store_purchases,complaints,satisfaction_score,last_purchase_days
76,C00077,43,Masculino,Universitaria,Viudo,677817.0,Metropolitana,2025-09-24,9,431912,2,11,2,3.0,296
136,C00137,150,Femenino,Postgrado,Casado,1152768.0,Metropolitana,2019-10-27,15,190776,7,7,1,4.0,300
280,C00281,43,Femenino,Postgrado,Viudo,NaN,Araucanía,2021-02-20,20,746418,9,7,0,3.0,107
319,C00320,40,Masculino,Media,Viudo,760088.0,Araucanía,2020-05-23,17,428171,7,9,1,4.0,187
411,C00412,28,Hombre,Técnica,Soltero,NaN,Metropolitana,2023-11-18,17,934178,7,10,1,5.0,228
513,C00514,31,Femenino,Universitaria,Casado,1167505.0,Santiago,2020-02-20,16,1660766,14,6,1,4.0,7
521,C00522,48,Masculino,NaN,Viudo,1486263.0,Metropolitana,2025-05-03,18,1099394,4,6,1,4.0,257
626,C00627,30,Masculino,Universitaria,Viudo,646963.0,Biobío,2021-02-27,12,694503,8,10,1,5.0,143
636,C00637,51,Masculino,Media,Divorciado,NaN,Araucanía,2025-12-18,16,1633022,16,7,1,3.0,145
660,C00661,35,Masculino,Universitaria,Soltero,1283428.0,Biobío,2025-06-27,17,280058,10,10,0,3.0,252
678,C00679,53,Femenino,Técnica,Casado,717460.0,Biobío,2022-06-13,10,693575,3,12,2,4.0,109
737,C00738,53,Masculino,Media,Soltero,826655.0,Santiago,2020-09-21,19,1713334,5,10,1,3.0,278
740,C00741,19,Femenino,Técnica,Casado,1714721.0,Araucanía,2019-08-19,20,50000000,5,10,2,4.0,108
761,C00762,43,Femenino,Media,Viudo,494754.0,Araucanía,2024-03-25,17,751725,9,12,0,4.0,45
811,C00812,36,Masculino,Media,Viudo,1512022.0,Metropolitana,2023-11-04,19,1175186,11,6,0,4.0,169
859,C00860,49,Femenino,Universitaria,Casado,729133.0,Valparaíso,2018-10-22,17,1186709,7,5,2,4.0,260
883,C00884,54,Femenino,Universitaria,Viudo,1338666.0,Biobío,2025-09-01,16,455683,5,12,0,4.0,264
899,C00900,32,Femenino,Técnica,Soltero,NaN,Araucanía,2023-02-16,12,333721,11,8,2,5.0,264
938,C00939,44,Masculino,Técnica,Casado,1789074.0,Biobío,2024-08-23,14,424648,8,14,2,5.0,68
973,C00974,34,Femenino,Universitaria,Viudo,512722.0,Metropolitana,2020-05-25,12,939370,6,14,2,3.0,347
1000,C00522,48,Masculino,NaN,Viudo,1486263.0,Metropolitana,2025-05-03,18,1099394,4,6,1,4.0,257
1001,C00738,53,Masculino,Media,Soltero,826655.0,Santiago,2020-09-21,19,1713334,5,10,1,3.0,278
1002,C00741,19,Femenino,Técnica,Casado,1714721.0,Araucanía,2019-08-19,20,50000000,5,10,2,4.0,108
1003,C00661,35,Masculino,Universitaria,Soltero,1283428.0,Biobío,2025-06-27,17,280058,10,10,0,3.0,252
1004,C00412,28,Hombre,Técnica,Soltero,NaN,Metropolitana,2023-11-18,17,934178,7,10,1,5.0,228
1005,C00679,53,Femenino,Técnica,Casado,717460.0,Biobío,2022-06-13,10,693575,3,12,2,4.0,109
1006,C00627,30,Masculino,Universitaria,Viudo,646963.0,Biobío,2021-02-27,12,694503,8,10,1,5.0,143
1007,C00514,31,Femenino,Universitaria,Casado,1167505.0,Santiago,2020-02-20,16,1660766,14,6,1,4.0,7
1008,C00860,49,Femenino,Universitaria,Casado,729133.0,Valparaíso,2018-10-22,17,1186709,7,5,2,4.0,260
1009,C00137,150,Femenino,Postgrado,Casado,1152768.0,Metropolitana,2019-10-27,15,190776,7,7,1,4.0,300
1010,C00812,36,Masculino,Media,Viudo,1512022.0,Metropolitana,2023-11-04,19,1175186,11,6,0,4.0,169
1011,C00077,43,Masculino,Universitaria,Viudo,677817.0,Metropolitana,2025-09-24,9,431912,2,11,2,3.0,296
1012,C00637,51,Masculino,Media,Divorciado,NaN,Araucanía,2025-12-18,16,1633022,16,7,1,3.0,145
1013,C00974,34,Femenino,Universitaria,Viudo,512722.0,Metropolitana,2020-05-25,12,939370,6,14,2,3.0,347
1014,C00939,44,Masculino,Técnica,Casado,1789074.0,Biobío,2024-08-23,14,424648,8,14,2,5.0,68
1015,C00900,32,Femenino,Técnica,Soltero,NaN,Araucanía,2023-02-16,12,333721,11,8,2,5.0,264
1016,C00281,43,Femenino,Postgrado,Viudo,NaN,Araucanía,2021-02-20,20,746418,9,7,0,3.0,107
1017,C00884,54,Femenino,Universitaria,Viudo,1338666.0,Biobío,2025-09-01,16,455683,5,12,0,4.0,264
1018,C00762,43,Femenino,Media,Viudo,494754.0,Araucanía,2024-03-25,17,751725,9,12,0,4.0,45
1019,C00320,40,Masculino,Media,Viudo,760088.0,Araucanía,2020-05-23,17,428171,7,9,1,4.0,187

In [28]:
#inconsistencias categóricas;
df['gender'].unique()

array(['Femenino', 'Masculino', 'femenino', 'Hombre', 'Otro', 'FEMENINO',
       'M'], dtype=object)

In [32]:
#valores extremos;
df.describe().T[['min', 'max']]

                         min         max
age                      5.0       150.0
income_clp         -500000.0  25000000.0
total_purchases          3.0        27.0
total_spent_clp     -30000.0  50000000.0
online_purchases         0.0        18.0
store_purchases          1.0        19.0
complaints              -1.0        50.0
satisfaction_score       0.0        10.0
last_purchase_days       2.0       364.0

Problemas de tipos de datos.

*     El campo genero tiene valores no esperados como hombre y femenino escrito de 3 formas distintas
*   Elemento de lista

## 6. Visualizaciones exploratorias

Genere visualizaciones que permitan comprender mejor los datos.

Cada gráfico debe incluir:

- título;
- interpretación;
- explicación de su relevancia.

In [ ]:
# Visualizaciones

## 7. Hallazgos principales

Resuma los principales descubrimientos obtenidos durante el análisis.

Considere:

- problemas encontrados;
- variables relevantes;
- decisiones necesarias antes de análisis posteriores.

## 8. Limitaciones del análisis

Describa limitaciones del análisis realizado.

Ejemplos:

- información faltante;
- supuestos realizados;
- análisis no incluidos.

## 9. Conclusiones

Responda:

- ¿El dataset está preparado para análisis posteriores?
- ¿Qué acciones recomienda antes de aplicar modelos o técnicas avanzadas?

## Declaración de uso de IA generativa

Complete esta sección si utilizó herramientas de IA durante el desarrollo.

**Herramienta utilizada:**Gemini

**Propósito del uso:**Consultas de código

**Forma en que validé y adapté la información obtenida:**Pedigo especificamente solo comandos en python